### ISSUE TITLE
Sweep: ParseError

### ISSUE THREAD

**Issue by axiades** [liberusoftware/cms-laravel#144]
### Details
/www/Projekt-Seiten/ProjectX/CMS$ php /usr/local/bin/composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
Class App\Filament\Admin\Resources\ContentResource located in ./app/Filament/App/Resources/ContentResource.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\ContentCategoryResource located in ./app/Filament/App/Resources/ContentCategoryResource.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\ActivationResource\Pages\ListActivations located in ./app/Filament/App/Resources/ActivationResource/Pages/ListActivations.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\ActivationResource\Pages\CreateActivation located in ./app/Filament/App/Resources/ActivationResource/Pages/CreateActivation.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\ActivationResource\Pages\EditActivation located in ./app/Filament/App/Resources/ActivationResource/Pages/EditActivation.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\ContentCategoryResource\Pages\CreateContentCategory located in ./app/Filament/App/Resources/ContentCategoryResource/Pages/CreateContentCategory.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\ContentCategoryResource\Pages\ListContentCategories located in ./app/Filament/App/Resources/ContentCategoryResource/Pages/ListContentCategories.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\ContentCategoryResource\Pages\EditContentCategory located in ./app/Filament/App/Resources/ContentCategoryResource/Pages/EditContentCategory.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\ActivationResource located in ./app/Filament/App/Resources/ActivationResource.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\ContentResource\Pages\EditContent located in ./app/Filament/App/Resources/ContentResource/Pages/EditContent.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\ContentResource\Pages\CreateContent located in ./app/Filament/App/Resources/ContentResource/Pages/CreateContent.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\ContentResource\Pages\ListContents located in ./app/Filament/App/Resources/ContentResource/Pages/ListContents.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\CommentResource\Pages\ListComments located in ./app/Filament/App/Resources/CommentResource/Pages/ListComments.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\CommentResource\Pages\CreateComment located in ./app/Filament/App/Resources/CommentResource/Pages/CreateComment.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\CommentResource\Pages\EditComment located in ./app/Filament/App/Resources/CommentResource/Pages/EditComment.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\CommentResource located in ./app/Filament/App/Resources/CommentResource.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\TagResource\Pages\CreateTag located in ./app/Filament/App/Resources/TagResource/Pages/CreateTag.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\TagResource\Pages\ListTags located in ./app/Filament/App/Resources/TagResource/Pages/ListTags.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\TagResource\Pages\EditTag located in ./app/Filament/App/Resources/TagResource/Pages/EditTag.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\CompanyResource\Pages\CreateCompany located in ./app/Filament/App/Resources/CompanyResource/Pages/CreateCompany.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\CompanyResource\Pages\EditCompany located in ./app/Filament/App/Resources/CompanyResource/Pages/EditCompany.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\CompanyResource\Pages\ListCompanies located in ./app/Filament/App/Resources/CompanyResource/Pages/ListCompanies.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\CompanyResource located in ./app/Filament/App/Resources/CompanyResource.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Resources\PageResource located in ./app/Filament/App/Resources/Resources/PageResource.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\AuthorResource located in ./app/Filament/App/Resources/AuthorResource.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\TagResource located in ./app/Filament/App/Resources/TagResource.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\AuthorResource\Pages\ListAuthors located in ./app/Filament/App/Resources/AuthorResource/Pages/ListAuthors.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\AuthorResource\Pages\CreateAuthor located in ./app/Filament/App/Resources/AuthorResource/Pages/CreateAuthor.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Filament\Admin\Resources\AuthorResource\Pages\EditAuthor located in ./app/Filament/App/Resources/AuthorResource/Pages/EditAuthor.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Http\Controllers\AdminForgotPasswordController located in ./app/Http/Controllers/ForgotPasswordController.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Http\Controllers\AdminResetPasswordController located in ./app/Http/Controllers/ResetPasswordController.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Http\Controllers\AdminLoginController located in ./app/Http/Controllers/LoginController.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Actions\Jetstream\DeleteUser located in ./app/Actions/Jetstream/DeleteUserWithTeams.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Actions\Socialstream\CreateUserFromProvider located in ./app/Actions/Socialstream/CreateUserWithTeamsFromProvider.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
Class App\Actions\Fortify\CreateNewUser located in ./app/Actions/Fortify/CreateNewUserWithTeams.php does not comply with psr-4 autoloading standard (rule: App\ => ./app). Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ParseError

  syntax error, unexpected token "public", expecting end of file

  at app/Models/Page.php:37
     33▕     {
     34▕         return $this->belongsTo(User::class);
     35▕     }
     36▕ }
  ➜  37▕     public function user()
     38▕     {
     39▕         return $this->belongsTo(User::class);
     40▕     }
     41▕ }

      +1 vendor frames

  2   app/Providers/AppServiceProvider.php:29
      Composer\Autoload\ClassLoader::loadClass()
      +7 vendor frames

  10  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Please Help me..

**Comment by curtisdelicata** [comment]
Under active development. Should be fixed in the week.

**Comment by curtisdelicata** [comment]
Fixed.
