### ISSUE TITLE
issues with fresh install erroring out

### ISSUE THREAD

**Issue by rborcherds** [liberusoftware/cms-laravel#173]
### Details
When running setup.sh, it errors out.   Here is the output from the run.

===== [PHP 8.3.9]
==================================

==================================
===== PREPARING YOUR PROJECT...
==================================

🎬 DEV ---> DID YOU WANT TO COPY THE .ENV.EXAMPLE TO .ENV? (y/n) y
Copying .env.example to .env 

==================================

🎬 DEV ---> DID YOU SETUP YOUR DATABASE CREDENTIALS IN THE .ENV FILE? (y/n) y
Perfect let's continue with the setup

==================================

🎬 DEV ---> COMPOSER INSTALL
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 175 installs, 0 updates, 0 removals
  - Installing voku/portable-ascii (2.0.1): Extracting archive
  - Installing symfony/polyfill-php80 (v1.30.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.30.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.30.0): Extracting archive
  - Installing phpoption/phpoption (1.9.2): Extracting archive
  - Installing graham-campbell/result-type (v1.1.2): Extracting archive
  - Installing vlucas/phpdotenv (v5.6.0): Extracting archive
  - Installing symfony/css-selector (v7.1.1): Extracting archive
  - Installing tijsverkoyen/css-to-inline-styles (v2.2.7): Extracting archive
  - Installing symfony/var-dumper (v7.1.2): Extracting archive
  - Installing symfony/polyfill-uuid (v1.30.0): Extracting archive
  - Installing symfony/uid (v7.1.1): Extracting archive
  - Installing symfony/deprecation-contracts (v3.5.0): Extracting archive
  - Installing symfony/routing (v7.1.1): Extracting archive
  - Installing symfony/process (v7.1.1): Extracting archive
  - Installing symfony/polyfill-php83 (v1.30.0): Extracting archive
.......

  - Installing spiral/roadrunner-cli (v2.6.0): Extracting archive
  - Installing roadrunner-php/roadrunner-api-dto (v1.8.0): Extracting archive
  - Installing spiral/roadrunner-http (v3.5.1): Extracting archive
  - Installing laravel/jetstream (v5.1.3): Extracting archive
  - Installing stephenjude/filament-jetstream (0.0.12): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ProviderRepository.php line 206:
                                                          
  Class "App\Providers\FortifyServiceProvider" not found  
                                                          

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

==================================

🎬 DEV ---> PHP ARTISAN KEY:GENERATE

In ProviderRepository.php line 206:
                                                          
  Class "App\Providers\FortifyServiceProvider" not found  
                                                          

==================================

🎬 DEV ---> php artisan migrate:fresh

In ProviderRepository.php line 206:
                                                          
  Class "App\Providers\FortifyServiceProvider" not found  
                                                          

==================================

🎬 DEV ---> php artisan db:seed

In ProviderRepository.php line 206:
                                                          
  Class "App\Providers\FortifyServiceProvider" not found  
                                                          

Database seeding failed.

**Comment by rborcherds** [comment]
**### Output from laravel.log**


[2024-07-22 16:19:33] local.ERROR: Class "App\Providers\FortifyServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"App\\Providers\\FortifyServiceProvider\" not found at /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:206)
[stacktrace]
#0 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(142): Illuminate\\Foundation\\ProviderRepository->createProvider()
#1 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest()
#2 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(843): Illuminate\\Foundation\\ProviderRepository->load()
#3 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(37): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#5 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#7 /var/www/html/cms-laravel/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"} 
[2024-07-22 16:19:33] local.ERROR: Class "App\Providers\FortifyServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"App\\Providers\\FortifyServiceProvider\" not found at /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:206)
[stacktrace]
#0 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(142): Illuminate\\Foundation\\ProviderRepository->createProvider()
#1 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest()
#2 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(843): Illuminate\\Foundation\\ProviderRepository->load()
#3 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(37): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#5 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#7 /var/www/html/cms-laravel/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"} 
[2024-07-22 16:19:34] local.ERROR: Class "App\Providers\FortifyServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"App\\Providers\\FortifyServiceProvider\" not found at /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:206)
[stacktrace]
#0 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(142): Illuminate\\Foundation\\ProviderRepository->createProvider()
#1 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest()
#2 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(843): Illuminate\\Foundation\\ProviderRepository->load()
#3 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(37): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#5 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#7 /var/www/html/cms-laravel/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"} 
[2024-07-22 16:19:34] local.ERROR: Class "App\Providers\FortifyServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"App\\Providers\\FortifyServiceProvider\" not found at /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:206)
[stacktrace]
#0 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(142): Illuminate\\Foundation\\ProviderRepository->createProvider()
#1 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\\Foundation\\ProviderRepository->compileManifest()
#2 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(843): Illuminate\\Foundation\\ProviderRepository->load()
#3 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(37): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#5 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(470): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /var/www/html/cms-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(194): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#7 /var/www/html/cms-laravel/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"}

**Comment by curtisdelicata** [comment]
Will resolve. Thank you for the report.

**Comment by curtisdelicata** [comment]
Fixed.
