### ISSUE TITLE
Posts table not found in migrations folder

### ISSUE THREAD

**Issue by rborcherds** [liberusoftware/cms-laravel#175]
### Details
When running for the first time after starting server and migrations are finished.

Posts table not found

![image](https://github.com/user-attachments/assets/c71c9b67-1545-4063-8967-1d4aa8a6c487)

![image](https://github.com/user-attachments/assets/c8bc48d4-212e-4944-9c55-d646efdc0825)

**Comment by curtisdelicata** [comment]
Fixed.
