### ISSUE TITLE
Error when running composer the first time.

### ISSUE THREAD

**Issue by rborcherds** [liberusoftware/cms-laravel#82]
### Details
When running composer for the first time to update all the dependencies, I get the following error:

In Macroable.php line 115:
                                                                          
  Method App\Filament\Resources\PageResource::isDeferred does not exist.  
                                                                          
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

![image](https://github.com/liberu-cms/cms-laravel/assets/607770/2c5ded2d-535a-4029-bf08-01499e30c31f)

**Comment by curtisdelicata** [comment]
Reverted changes to composer. Merged the is Deferred method. Please confirm

**Comment by rborcherds** [comment]
Filament did upgrade during composer, but it did not resolve the error

![image](https://github.com/liberu-cms/cms-laravel/assets/607770/67bfbc3f-b08b-41bb-b8bc-97638c4b55c5)

**Comment by curtisdelicata** [comment]
@borcherds-ralph this will be fixed next week. We are focusing on stability next week on all Liberu projects.

**Comment by curtisdelicata** [comment]
Try pulling. I think I already solved.

**Comment by rborcherds** [comment]
Now I am getting this:


 BadMethodCallException 

  Method App\Filament\Resources\PageResource::register does not exist.

  at vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:115
    111▕      */
    112▕     public function __call($method, $parameters)
    113▕     {
    114▕         if (! static::hasMacro($method)) {
  ➜ 115▕             throw new BadMethodCallException(sprintf(
    116▕                 'Method %s::%s does not exist.', static::class, $method
    117▕             ));
    118▕         }
    119▕ 

  i   Bad Method Call: Did you mean App\Filament\Resources\PageResource::registerRoutes() ? 

      +7 vendor frames 

  8   artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1


![image](https://github.com/liberu-cms/cms-laravel/assets/607770/4a9b6abd-4696-46fc-88b1-9b755ca68936)

**Comment by curtisdelicata** [comment]
Finally fixed and major updates. @borcherds-ralph
